.TH UU 1
.SH NAME
\fBuu\fR \- unsorted uniq

.SH SYNOPSIS
\fBuu\fR

.SH DESCRIPTION
\fBuu\fR prints only the first occurrence of an input line.
The input does not have to be sorted.
Any arguments are ignored.

.SH EXAMPLE
\fBecho -e 'naaas\\npaas\\nras\\npaas\\ntaas' | uu\fR prints
.IP
naaas
.br
paas
.br
ras
.br
taas

.SH BUGS
The awk version is too simple to contain any serious bugs,
the C version was tested with uno and valgrind.

murmurhashes collide. the awk version uses too much memory.

.SH AUTHOR
a.regenfuss@gmx.de
